<%@ page language="java" pageEncoding="UTF-8"%>
<%@ include file="/commons/taglibs.jsp"%>
<%-- <%@ include file="/commons/jquerylibs.jsp"%> --%>
<html>
	<head>
		<%-- <script type="text/javascript" src="${base}/report/js/highchart/highcharts.js"></script> --%>
	</head>
	<body>
		<div class="section">
			<div class="filters section" id="FilterTabs">
			    <div class="tabs filter-tabs">
			        <div class="" style="width: 100%;">
			        	<div class="section-title l">详细数据:</div>
			            <a class="download-report r" id="DownloadReport" href="javascript:void(0)">导出EXCEL文件</a>
					</div>
			    </div>
			</div>
			<div id="table" class="l" style="width:100%;">
				<table class="table">
					<thead style="background-color: windowframe;color: white;">
						<tr id="" class="">
							<td class="table-index sortable"><div class="td-content"><label>日期</label></div></td>
							<td class="number sortable" ><div class="td-content"><label>新用户</label></div></td>
							<td class="ratio sortable"><div class="td-content"><label>新用户占比</label></div></td>
							<td class="number sortable"><div class="td-content"><label>启动用户</label></div></td>
							<td class="number sortable"><div class="td-content"><label>启动次数</label></div></td>
							<td class="time sortable"><div class="td-content"><label>每次使用时长</label></div></td>
							<td class="time sortable"><div class="td-content"><label>每人使用时长</label></div></td>
						</tr>
					</thead>
					<tbody>
						<tr id="tangram-table--TANGRAM__b-tr_0" class="line"><td id="simple_date_title" data="" class="table-index" rowspan="" colspan=""><div title="" class="td-content">2014-11-05</div></td><td id="new_user_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">402</div></td><td id="new_user_ratio" data="" class="ratio" rowspan="" colspan=""><div title="" class="td-content">8.27%</div></td><td id="user_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">4,861</div></td><td id="session_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">11,044</div></td><td id="average_session_time" data="" class="time" rowspan="" colspan=""><div title="" class="td-content">00:03:21</div></td><td id="session_time_per_person" data="" class="time" rowspan="" colspan=""><div title="" class="td-content">00:07:38</div></td></tr>
						<tr id="tangram-table--TANGRAM__b-tr_1" class="line"><td id="simple_date_title" data="" class="table-index" rowspan="" colspan=""><div title="" class="td-content">2014-11-04</div></td><td id="new_user_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">1,527</div></td><td id="new_user_ratio" data="" class="ratio" rowspan="" colspan=""><div title="" class="td-content">10.64%</div></td><td id="user_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">14,348</div></td><td id="session_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">38,613</div></td><td id="average_session_time" data="" class="time" rowspan="" colspan=""><div title="" class="td-content">00:03:17</div></td><td id="session_time_per_person" data="" class="time" rowspan="" colspan=""><div title="" class="td-content">00:08:50</div></td></tr>
						<tr id="tangram-table--TANGRAM__b-tr_2" class="line"><td id="simple_date_title" data="" class="table-index" rowspan="" colspan=""><div title="" class="td-content">2014-11-03</div></td><td id="new_user_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">1,450</div></td><td id="new_user_ratio" data="" class="ratio" rowspan="" colspan=""><div title="" class="td-content">10.16%</div></td><td id="user_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">14,272</div></td><td id="session_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">38,623</div></td><td id="average_session_time" data="" class="time" rowspan="" colspan=""><div title="" class="td-content">00:03:18</div></td><td id="session_time_per_person" data="" class="time" rowspan="" colspan=""><div title="" class="td-content">00:08:58</div></td></tr>
						<tr id="tangram-table--TANGRAM__b-tr_3" class="line"><td id="simple_date_title" data="" class="table-index" rowspan="" colspan=""><div title="" class="td-content">2014-11-02</div></td><td id="new_user_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">1,727</div></td><td id="new_user_ratio" data="" class="ratio" rowspan="" colspan=""><div title="" class="td-content">11.22%</div></td><td id="user_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">15,397</div></td><td id="session_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">41,850</div></td><td id="average_session_time" data="" class="time" rowspan="" colspan=""><div title="" class="td-content">00:03:15</div></td><td id="session_time_per_person" data="" class="time" rowspan="" colspan=""><div title="" class="td-content">00:08:52</div></td></tr>
						<tr id="tangram-table--TANGRAM__b-tr_4" class="line"><td id="simple_date_title" data="" class="table-index" rowspan="" colspan=""><div title="" class="td-content">2014-11-01</div></td><td id="new_user_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">1,610</div></td><td id="new_user_ratio" data="" class="ratio" rowspan="" colspan=""><div title="" class="td-content">10.64%</div></td><td id="user_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">15,138</div></td><td id="session_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">42,518</div></td><td id="average_session_time" data="" class="time" rowspan="" colspan=""><div title="" class="td-content">00:03:15</div></td><td id="session_time_per_person" data="" class="time" rowspan="" colspan=""><div title="" class="td-content">00:09:08</div></td></tr>
						<tr id="tangram-table--TANGRAM__b-tr_5" class="line"><td id="simple_date_title" data="" class="table-index" rowspan="" colspan=""><div title="" class="td-content">2014-10-31</div></td><td id="new_user_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">1,894</div></td><td id="new_user_ratio" data="" class="ratio" rowspan="" colspan=""><div title="" class="td-content">12.68%</div></td><td id="user_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">14,935</div></td><td id="session_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">39,963</div></td><td id="average_session_time" data="" class="time" rowspan="" colspan=""><div title="" class="td-content">00:03:18</div></td><td id="session_time_per_person" data="" class="time" rowspan="" colspan=""><div title="" class="td-content">00:08:50</div></td></tr>
						<tr id="tangram-table--TANGRAM__b-tr_6" class="line"><td id="simple_date_title" data="" class="table-index" rowspan="" colspan=""><div title="" class="td-content">2014-10-30</div></td><td id="new_user_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">1,943</div></td><td id="new_user_ratio" data="" class="ratio" rowspan="" colspan=""><div title="" class="td-content">13.02%</div></td><td id="user_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">14,923</div></td><td id="session_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">40,183</div></td><td id="average_session_time" data="" class="time" rowspan="" colspan=""><div title="" class="td-content">00:03:17</div></td><td id="session_time_per_person" data="" class="time" rowspan="" colspan=""><div title="" class="td-content">00:08:50</div></td></tr>
						<tr id="tangram-table--TANGRAM__b-tr_7" class="line"><td id="simple_date_title" data="" class="table-index" rowspan="" colspan=""><div title="" class="td-content">2014-10-29</div></td><td id="new_user_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">1,372</div></td><td id="new_user_ratio" data="" class="ratio" rowspan="" colspan=""><div title="" class="td-content">9.51%</div></td><td id="user_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">14,421</div></td><td id="session_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">39,809</div></td><td id="average_session_time" data="" class="time" rowspan="" colspan=""><div title="" class="td-content">00:03:18</div></td><td id="session_time_per_person" data="" class="time" rowspan="" colspan=""><div title="" class="td-content">00:09:06</div></td></tr>
						<tr id="tangram-table--TANGRAM__b-tr_8" class="line"><td id="simple_date_title" data="" class="table-index" rowspan="" colspan=""><div title="" class="td-content">2014-10-28</div></td><td id="new_user_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">1,400</div></td><td id="new_user_ratio" data="" class="ratio" rowspan="" colspan=""><div title="" class="td-content">9.66%</div></td><td id="user_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">14,486</div></td><td id="session_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">39,567</div></td><td id="average_session_time" data="" class="time" rowspan="" colspan=""><div title="" class="td-content">00:03:20</div></td><td id="session_time_per_person" data="" class="time" rowspan="" colspan=""><div title="" class="td-content">00:09:08</div></td></tr>
						<tr id="tangram-table--TANGRAM__b-tr_9" class="line"><td id="simple_date_title" data="" class="table-index" rowspan="" colspan=""><div title="" class="td-content">2014-10-27</div></td><td id="new_user_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">1,460</div></td><td id="new_user_ratio" data="" class="ratio" rowspan="" colspan=""><div title="" class="td-content">9.36%</div></td><td id="user_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">14,586</div></td><td id="session_count" data="" class="number" rowspan="" colspan=""><div title="" class="td-content">35,517</div></td><td id="average_session_time" data="" class="time" rowspan="" colspan=""><div title="" class="td-content">00:03:40</div></td><td id="session_time_per_person" data="" class="time" rowspan="" colspan=""><div title="" class="td-content">00:07:05</div></td></tr>
					</tbody>
				</table>
			</div>
		</div>
	</body>
 <script type="text/javascript">
</script> 
</html>
			