# Host: 127.0.0.1  (Version: 5.5.36)
# Date: 2014-11-25 18:08:07
# Generator: MySQL-Front 5.3  (Build 4.170)

/*!40101 SET NAMES utf8 */;

#
# Structure for table "DIM_COUNTRY"
#

DROP TABLE IF EXISTS `DIM_COUNTRY`;
CREATE TABLE `DIM_COUNTRY` (
  `AB2` varchar(2) NOT NULL,
  `AB3` varchar(3) NOT NULL,
  `CODE` int(10) unsigned NOT NULL,
  `AB` varchar(64) NOT NULL,
  `NAME` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`AB2`),
  UNIQUE KEY `IDX_DIM_CONTRY_AB2` (`AB2`),
  UNIQUE KEY `IDX_DIM_CONTRY_AB3` (`AB3`),
  UNIQUE KEY `IDX_DIM_CONTRY_CODE` (`CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Data for table "DIM_COUNTRY"
#

INSERT INTO `DIM_COUNTRY` VALUES ('AD','AND',20,'安道尔 Andorra','安道尔公国 Principality of Andorra'),
('AE','ARE',784,'阿联酋 United Arab Emirates','拉伯联合酋长国 United Arab Emirates'),
('AF','AFG',4,'阿富汗 Afghanistan','阿富汗伊斯兰国 Islamic State of Afghanistan'),
('AG','ATG',28,'安提瓜和巴布达 Antigua and Barbuda','安提瓜和巴布达 Antigua and Barbuda'),
('AI','AIA',660,'安圭拉 Anguilla','安圭拉 Anguilla'),
('AL','ALB',8,'阿尔巴尼亚 Albania','阿尔马尼亚共和国 Republic of Albania'),
('AM','ARM',51,'亚美尼亚 Armenia','亚美尼亚共和国 Republic of Armenia'),
('AN','ANT',530,'荷属安的列斯 Netherlands Antilles','荷属安的列斯 Netherlands Antilles'),
('AO','AGO',24,'安哥拉 Angola','安哥拉共和国 Republic of Angola'),
('AQ','ATA',10,'南极洲 Antarctica','南极洲 Antarctica'),
('AR','ARG',32,'阿根廷 Argentina','阿根廷共和国 Republic of Argentina'),
('AS','ASM',16,'美属萨摩亚 American Samoa','美属萨摩亚 American Samoa'),
('AT','AUT',40,'奥地利 Austria','奥地利共和国 Republic of Austria'),
('AU','AUS',36,'澳大利亚 Australia','澳大利亚联邦 Commonwealth of Australia'),
('AW','ABW',533,'阿鲁巴 Aruba','阿鲁巴 Aruba'),
('AZ','AZE',31,'阿塞拜疆 Azerbaijan','阿塞拜疆共和国 Republic of Azerbaijan'),
('BA','BIH',70,'波斯尼亚和黑塞哥维那 Bosnia and Herzegovina','波斯尼亚和黑塞哥维那共和国 Republic of Bosnia and Herzegovina'),
('BB','BRB',52,'巴巴多斯 Barbados','巴巴多斯 Barbados'),
('BD','BGD',50,'孟加拉国 Bangladesh','孟加拉人民共和国 People\'s Republic of Bangladesh'),
('BE','BEL',56,'比利时 Belgium','比利时王国 Kingdom of belgium'),
('BF','BFA',854,'布基纳法索 Burkina Faso','布基纳法索 Burkina Faso'),
('BG','BGR',100,'保加利亚 Bulgaria','保加利亚共和国 Republic ov Bulgaria'),
('BH','BHR',48,'巴林 Bahrain','巴林国 State of Bahrain'),
('BI','BDI',108,'布隆迪 Burundi','布隆迪共和国 Republic of Burundi'),
('BJ','BEN',204,'贝宁 Benin','贝宁共和国 Republic of Benin'),
('BM','BMU',60,'百慕大 Bermuda','百慕大群岛 Bermuda Islands'),
('BN','BRN',96,'文莱 Brunei Darussalam','文莱达鲁萨兰国 Brunei Darussalam'),
('BO','BOL',68,'玻利维亚 Bolivia','玻利维亚共和国 Republic of Bolivia'),
('BR','BRA',76,'巴西 Brazil','巴西联邦共和国 Federative Republic of Brazil'),
('BS','BHS',44,'巴哈马 Bahamas','巴哈马联邦 Commonwealth of the Bahamas'),
('BT','BTN',64,'不丹 Bhutan','不丹王国 Kingdom of Bhutan'),
('BV','BVT',74,'布维岛 Bouvet Island','布维岛 Bouvet Island'),
('BW','BWA',72,'博茨瓦纳 Botswana','博茨瓦纳共和国 Republic of Botswana'),
('BY','BLR',112,'白俄罗斯 Belarus','白俄罗斯共和国 Republic of Belarus'),
('BZ','BLZ',84,'伯利兹 Belize','伯利兹 Belize'),
('CA','CAN',124,'加拿大 Canada','加拿大 Canada'),
('CC','CCK',166,'科科斯(基林)群岛 Cocos(Keeling) Islands','科科斯(基林)群岛 Cocos(Keeling) Islands'),
('CF','CAF',140,'中非 Central Africa','中非共和国 Central African Republic'),
('CG','COG',178,'刚果 Congo','刚果共和国 Republic of Congo'),
('CH','CHE',756,'瑞士 Switzerland','瑞士联邦 Swiss Confederation'),
('CI','CIV',384,'科特迪瓦 Cote d\'Ivoire','科特迪瓦共和国 Republic of Cote d\'Ivire'),
('CK','COK',184,'库克群岛 Cook Islands','库克群岛 Cook Islands'),
('CL','CHL',152,'智利 Chile','智利共和国 Republic of Chile'),
('CM','CMR',120,'喀麦隆 Cameroon','喀麦隆共和国 Republic of Cameroon'),
('CN','CHN',156,'中国 China','中华人民共和国 People\'s Republic of China'),
('Co','COL',170,'哥伦比亚 Colombia','哥伦比亚共和国 Republic of Colombia'),
('CR','CR',188,'哥斯达黎加 Costa Rica','哥斯达黎加共和国 Republic of Costa Rica'),
('CS','CSR',162,'圣诞岛 Christmas Island','圣诞岛 Christmas Island'),
('CT','CTN',158,'中国台湾 Taiwan,China','中国台湾 Chinese Taiwan'),
('CU','CUB',192,'古巴 Cuba','古巴共和国 Republic of Cuba'),
('CV','CPV',132,'佛得角 Cape Verde','佛得角共和国 Republic of Cape Verde'),
('CY','CYP',196,'塞浦路斯 Cyprus','塞浦路斯共和国 Republic of Cyprus'),
('CZ','CZE',203,'捷克 Czech Repoublic','捷克共和国 Czech Republic'),
('DE','DEU',276,'德国 Germany','德意志联邦共和国 Federal Republic of Germany'),
('DJ','DJI',262,'吉布提 Djibouti','吉布提共和国 Republic of Djibouti'),
('DK','DNK',208,'丹麦 Denmark','丹麦王国 Kingdom of Denmark'),
('DM','DMA',212,'多米尼克 Dominica','多米尼克联邦 Commonwealth of Dominica'),
('DO','DOM',214,'多米尼加共和国 Dominican Republic','多米尼加共和国 Dominican Republic'),
('DZ','DZA',12,'阿尔及利亚 Algeria','阿尔及利亚民主人民共和国 Democratic People\'s Republic of Algeria'),
('EC','ECU',218,'厄瓜多尔 Ecuador','厄瓜多尔共和国 Republic of Ecuador'),
('EE','EST',233,'爱沙尼亚 Estonia','爱沙尼亚共和国 Republic of Estonia'),
('EG','EGY',818,'埃及 Egypt','阿拉伯埃及共和国 Arab Republic of Egypt'),
('EH','ESH',732,'西撒哈拉 Western Sahara','西撒哈拉 Western Sahara'),
('ER','ERI',232,'厄立特里亚 Eritrea','厄立特里亚国 State of Eritrea'),
('ES','ESP',724,'西班牙 Spain','西班牙 Spain'),
('ET','ETH',231,'埃塞俄比亚 Ethiopia','埃塞俄比亚 Ethiopia'),
('FI','FIN',246,'芬兰 Finland','芬兰共和国 Republic of Finland'),
('FJ','FJI',242,'斐济 Fiji','斐济共和国 Republic of Fiji'),
('FK','FLK',238,'马尔维纳斯群岛(福克兰群岛) Malvinas Islands (Falkland Islands)','马尔维纳斯群岛(福克兰群岛) Malvinas islands (Falkland Islands)'),
('FM','FSM',583,'密克罗尼西亚 Micronesia','密克罗尼西亚联邦 Federated States of Micronesia'),
('FO','FRO',234,'法罗群岛 Faroe Islands','法罗群岛 Faroe Islands'),
('FR','FRA',250,'法国 France','法兰西共和国 French Republic'),
('GA','GAB',266,'加蓬 Gabon','加蓬共和国 Gabonese Republic'),
('GB','GBR',826,'英国 United Kingdom','大不列颠及北爱尔兰联合王国 United Kingdom of Great Britain and Northern irela'),
('GD','GRD',308,'格林纳达 Grenada','格林纳达 Grenada'),
('GE','GEO',268,'格鲁吉亚 Georgia','格鲁吉亚共和国 Republic of Georgia'),
('GF','GUF',254,'法属圭亚那 French Guiana','法属圭亚那 French Guiana'),
('GH','GHA',288,'加纳 Ghana','加纳共和国 Republic of Ghana'),
('GI','GIB',292,'直布罗陀 Gibraltar','直布罗陀 Gibraltar'),
('GL','GRL',304,'格陵兰 Greenland','格陵兰 Greenland'),
('GM','GMB',270,'冈比亚Gambia','冈比亚共和国 Republic of Gambia'),
('GN','GIN',324,'几内亚 Guinea','几内亚共和国 Republic of Guinea'),
('GP','GLP',312,'瓜德罗普 Guadeloupe','瓜德罗普 Guadeloupe'),
('GQ','GNQ',226,'赤道几内亚 Equatorial Guinea','赤道几内亚共和国 Republic of Equatorial Guinea'),
('GR','GRC',300,'希腊 Greece','希腊共和国 Hellenic Republic'),
('GS','SGS',239,'南乔治亚岛和南桑德韦奇岛 South Georgia and South Sandwich Islands','南乔治亚岛和南桑德韦奇岛 South Georgia and South Sandwich Islands'),
('GT','GTM',320,'危地马拉 Guatemala','危地马拉共和国 Republic of Guatemala'),
('GU','GUM',316,'关岛 Guam','关岛 Guam'),
('GW','GNB',624,'几内亚比绍 Guine-bissau','几内亚比绍共和国 Republic of Guine-bissau'),
('GY','GUY',328,'圭亚那 Guyana','圭亚那合作共和国 Cooperative Republic of Guyana'),
('HK','HKG',344,'香港 Hong Kong','香港 Hong Kong'),
('HM','HMD',334,'赫德岛和麦克唐纳岛 Heard islands and Mc Donald Islands','赫德岛和麦克唐纳岛 Heard islands and Mc Donald Islands'),
('HN','HND',340,'洪都拉斯 Honduras','洪都拉斯共和国 Republic of honduras'),
('HR','HRV',191,'克罗地亚 Croatia','克罗地亚共和国 Republic of Croatia'),
('HT','HTI',332,'海地 Haiti','海地共和国 Republic of Haiti'),
('HU','HUN',348,'匈牙利 Hungary','匈牙利共和国 Republic of Hungary'),
('ID','IDN',360,'印度尼西亚 Indonesia','印度尼西亚共和国 Republic of Indonesia'),
('IE','IRL',372,'爱尔兰 Ireland','爱尔兰 Ireland'),
('IL','ISR',376,'以色列 Israel','以色列国 State of Israel'),
('IN','IND',356,'印度 India','印度共和国 Republic of India'),
('IO','IOT',86,'英属印度洋领土 British indian Ocean Ter-ritory','英属印度洋领土 British Indian Ocean Territory'),
('IQ','IRQ',368,'伊拉克 Iraq','伊拉克共和国 Republic of Iraq'),
('IR','IRN',364,'伊朗 Iran','伊朗伊斯兰共和国 Islamic Rupublic of Iran'),
('IS','ISL',352,'冰岛 Iceland','冰岛共和国 Republic of Iceland'),
('IT','ITA',380,'意大利 Italy','意大利共和国 Republic of Italy'),
('JM','JAM',388,'牙买加 Jamaica','牙买加 Jamaica'),
('JO','JOR',400,'约旦 Jordan','约旦哈希姆王国 Hashemite Kingdom of Jordan'),
('JP','JPN',392,'日本 Japan','日本国 Japan'),
('KE','KEN',404,'肯尼亚 Kenya','肯尼亚共和国 Republic of Kenya'),
('KG','KGZ',417,'吉尔吉斯斯坦 Kyrgyzstan','吉尔吉斯共和国 Kyrgyz Republic'),
('KH','KHM',116,'柬埔寨 Cambodia','柬埔寨王国 Kingdom of Cambodia'),
('KI','KIR',296,'基里巴斯 Kiribati','基里巴斯共和国 Republic of Kiribati'),
('KM','COM',174,'科摩罗 Comoros','科摩罗伊斯兰联邦共和国 Federal Islamic Republic of the Co-moros'),
('KN','KNA',659,'圣基茨和尼维斯 Saint Kitts and nevis','圣革茨和尼维斯联邦 Federation of Saint Kitts and nevis'),
('KP','PRK',408,'朝鲜 Korea,Democratic People\'s Republic of','朝鲜民主主义人民共和国 Democratic People\'s Republic of Ko-rea'),
('KR','KOR',410,'韩国 Korea,Republic of','大韩民国 Republic of Korea'),
('KW','KWT',414,'科威特 Kuwait','科威特国 State of Kuwait'),
('KY','CYM',136,'开曼群岛 Cayman Islands','开曼群岛 Cayman Islands'),
('KZ','KAZ',398,'哈萨克斯坦 Kazakhstan','哈萨克斯坦共和国 Republic of Kazakhstan'),
('LA','LAO',418,'老挝 Lao','老挝人民民主共和国 Lao People\'s Democratic Republic'),
('LB','LBN',422,'黎巴嫩 Lebanon','黎巴嫩共和国 Republic of Lebanon'),
('LC','LCA',662,'圣卢西亚 Saint lucia','圣卢西亚 Saint Lucia'),
('LI','LIE',438,'列支敦士登 Liechtenstein','列支敦士登公国 Principality of Liechtenstein'),
('LK','LKA',144,'斯里兰卡 Sri Lanka','斯里兰卡民主社会主义共和国 Democratic Socialist Republic of Srilanka'),
('LR','LBR',430,'利比里亚 Liberia','利比里亚共和国 Republic of Liberia'),
('LS','LSO',426,'莱索托 Lesotho','莱索托王国 Kingdom of Lesoto'),
('LT','LTU',440,'立陶宛 Lithuania','立陶宛共和国 Republic of Lithuania'),
('LU','LUX',442,'卢森堡 Luxembourg','卢森堡大公国 Grand Duchy of Luxembourg'),
('LV','LVA',428,'拉脱维亚 Latvia','拉脱维亚共和国 Republic of Latvia'),
('LY','LBY',434,'利比亚 Libya','大阿拉伯利比亚人民社会主义民众国 Great Socialist People\'s Libyan Arab jamahiriya'),
('MA','MAR',504,'摩洛哥 Morocco','摩洛哥王国 Kingdom of Morocco'),
('MC','MCO',492,'摩纳哥 Monaco','摩纳哥公国 Principality of Monaco'),
('MD','MDA',498,'摩尔多瓦 Moldova','摩尔多瓦共和国 Republic of Moldova'),
('MG','MDG',450,'马达加斯加 Madagascar','马达加斯加共和国 Republic of Madagascar'),
('MH','MHL',584,'马绍尔群岛 Marshall Islands','马绍尔群岛共和国 Republic of the marshall Islands'),
('MK','MKD',807,'马斯顿 Macedonia','马其顿共和国 Republic of Macedonia'),
('ML','MLI',466,'马里 Mali','马里共和国 Republic of Mali'),
('MM','MMR',104,'缅甸 Myanmar','缅甸联邦 Union of Myanmar'),
('MN','MNG',496,'蒙古 Mongolia','蒙古国 Mongolia'),
('MO','MAC',446,'澳门 Macau','澳门 Macau'),
('MP','MNP',580,'北马里亚纳 Northern Marianas','北马里亚纳自由联邦 Commonwealth of the Northern Marianas'),
('MQ','MTQ',474,'马提尼克 Martinique','马提尼克 Martinique'),
('MR','MRT',478,'毛里塔尼亚 Mauritania','毛里求斯共和国 Republic of Mauritius'),
('MS','MSR',500,'蒙特塞拉特 Montserrat','蒙特塞拉特 Montserrat'),
('MT','MLT',470,'马耳他 Malta','马耳他共和国 Republic of Malta'),
('MU','MUS',480,'毛里求斯 Mauritius','毛里求斯共和国 Republic of Mauritius'),
('MV','MDV',462,'马尔代夫 Maldives','马尔代夫共和国 Republic of maldives'),
('MW','MWI',454,'马拉维 Malawi','马拉维共和国 Republic of Malawi'),
('MX','MEX',484,'墨西哥 Mexico','墨西哥合众国 United States of Mexico'),
('MY','MYS',458,'马来西亚 Malaysia','马来西亚 Malaysia'),
('MZ','MOZ',508,'莫桑比克 Mozambique','莫桑比克共和国 Republic of Mozambique'),
('NA','NAM',516,'纳米比亚 Namibia','纳米比亚共和国 Republic of Namibia'),
('NC','NCL',540,'新喀里多尼亚 New Caledonia','新喀里多尼亚 New Caledonia'),
('NE','NER',562,'尼日尔 Niger','尼日尔共和国 Republic of Niger'),
('NF','NFK',574,'诺福克岛 Norfolk Island','诺福克岛 Norfolk Island'),
('NG','NGA',566,'尼日利亚 Nigeria','尼日利亚联邦共和国 Federal Republic of Nigeria'),
('NI','NIC',558,'尼加拉瓜 Nicaragua','尼加拉瓜共和国 Republic of Nicaragua'),
('NL','NLD',528,'荷兰 Netherlands','荷兰王国 Kingdom of the Netherlands'),
('NO','NOR',578,'挪威 Norway','挪威王国 Kingdom of Norway'),
('NP','NPL',524,'尼泊尔 Nepal','尼泊尔王国 Kingdom of Nepal'),
('NR','NRU',520,'瑙鲁 Nauru','瑙鲁共和国 Republic of Nauru'),
('NU','NIU',570,'纽埃 Niue','纽埃 Niue'),
('NZ','NZL',554,'新西兰 New Zealand','新西兰 New Zealand'),
('OM','OMN',512,'阿曼 Oman','阿曼苏丹国 Sultanate of Oman'),
('PA','PAN',591,'巴拿马 Panama','巴拿马共和国 Republic of Panama'),
('PE','PER',604,'秘鲁 Peru','秘鲁共和国 Republic of Peru'),
('PF','PYF',258,'法属波利尼西亚 French Polynesia','法属波利尼西亚 French Polynesia'),
('PG','PNG',598,'巴布亚新几内亚 Papua New Guinea','巴布亚新几内亚独立国 Independent State of Papua New Guinea'),
('PH','PHL',608,'菲律宾 Philippines','菲律宾共和国 Republic of the Philippines'),
('PK','PAK',586,'巴基斯坦 Pakistan','巴基斯坦伊斯兰共和国 Islamic Republic of Pakistan'),
('PL','POL',616,'波兰 Poland','波兰共和国 Republic of Poland'),
('PM','SPM',666,'圣皮埃尔和密克隆 Saint Pierre and Miquelon','圣皮埃尔和密克隆 Saint Pierre and Miquelon'),
('PN','PCN',612,'皮特凯恩群岛 Pitcairn Islands Group','皮竺凯恩群岛 Pitcairn Islands Group'),
('PR','PRI',630,'波多黎各 Puerto Rico','波多黎各自由联邦 Commonwealth of Puerto Rico'),
('PS','PST',374,'巴勒斯坦 Palestine','巴勒斯坦国 State of Palestine'),
('PT','PRT',620,'葡萄牙 Portugal','葡萄牙共和国 Pirtuguese Republic'),
('PW','PLW',585,'贝劳 Palau','贝劳共和国 Republic of Palau'),
('PY','PRY',600,'巴拉圭 Paraguay','巴拉圭共和国 Republic of Paraguay'),
('QA','QAT',634,'卡塔尔 Qatar','卡塔尔国 State of Qatar'),
('RE','REU',638,'留尼汪 Reunion','留尼汪 Reunion'),
('RO','ROM',642,'罗马尼亚 Romania','罗马尼亚 Romania'),
('RU','RUS',643,'俄罗斯 Russia','俄罗斯联邦 Russian Federation'),
('RW','RWA',646,'卢旺达 Rwanda','卢旺达共和国 Republic of Rwanda'),
('SA','SAU',682,'沙竺阿拉伯 Saudi Arabia','沙特阿拉伯王国 Kingdom of Saudi Arabia'),
('SB','SLB',90,'所罗门群岛 Solomon Islands','年罗门群岛 Solomon Islands'),
('SC','SYC',690,'塞舌尔 Seychells','塞舌尔共和国 Republic of Seychelles'),
('SD','SDN',736,'苏丹 Sudan','苏丹共和国 Republic of the Sudan'),
('SE','SWE',752,'瑞典 Sweden','瑞典王国 Kingdom of Sweden'),
('SG','SGP',702,'新加坡 Singapore','新加坡共和国 Republic of Singapore'),
('Sh','SHN',654,'圣赫勒拿 Saint helena','对赫勒拿 Saint Helena'),
('SI','SVN',705,'斯洛文尼亚 Slovenia','斯洛文尼亚共和国 Republic of Slovenia'),
('SJ','SJM',744,'斯瓦尔巴群岛 Svalbard and jan Mayen Islands','斯瓦尔巴群岛 Svalbard and Jan mayen islands'),
('SK','SVK',703,'斯洛伐克 Slovakia','斯洛伐克共和国 Slovak Republic'),
('SL','SLE',694,'塞拉利昂 Sierra leone','塞拉利昂共和国 Republic of Sierra Leone'),
('SM','SMR',674,'圣马力诺 San Marion','圣马力诺共和国 Republic of San Marino'),
('SN','SEN',686,'塞内加尔 Senegal','塞内加尔共和国 Republic of Senegal'),
('SO','SOM',706,'索马里 Somalia','索马里共和国 Somali Republic'),
('SR','SUR',740,'苏里南 Suriname','苏里南共和国 Republic of Suriname'),
('St','STp',678,'圣多美和普林西比 Sao Tome and Principe','圣多美和普林西比民主共和国 Democratic Republic of Sao Tome and Principe'),
('SV','SLV',222,'萨尔瓦多 El Salvador','萨尔瓦多共和国 Republic of El Salvador'),
('SY','SYR',760,'叙利亚 Syria','阿拉伯叙利亚共和国 Syrian Arab Republic'),
('SZ','SWZ',748,'斯威士兰 Swaziland','斯威士兰王国 Kingdom of Swaziland'),
('TC','TCA',796,'特克斯科斯群岛 Turks and Caicos Islands','特克斯和凯科斯群岛 Turks and Caicos Islands'),
('TD','TCD',148,'乍得 Chad','乍得共和国 Republic of Chad'),
('TF','ATF',260,'法属南部领土 French Southern Territo-ries','法属南部领土 French Southern Territories'),
('TG','TGO',768,'多哥 Togo','多哥共和国 Republic of Tago'),
('TH','THA',764,'泰国 Thailand','泰王国 Kingdom of Thailand'),
('TJ','TJK',762,'塔吉克斯坦 Tajikistan','塔吉克斯坦共和国 Republic of Tajikistan'),
('TK','TKL',772,'托克劳 Tokelau','托克劳 Tokelau'),
('TM','TKM',795,'土库曼斯坦 Turkmenistan','土库曼斯坦 Turkmenistan'),
('TN','TUN',788,'突尼斯 Tunisia','突尼斯共和国 Republic of Tunisia'),
('TO','TON',776,'汤加 Tonga','汤加王国 Kingdom of Tonga'),
('TP','TMP',626,'东帝汶 East Timor','东帝汶 East Timor'),
('TR','TUR',792,'土耳其 Turkey','土耳其共和国 Republic of Turkey'),
('TT','TTO',780,'特立尼达和多巴哥 Trinidad and Tobago','特立尼达和多巴哥共和国 Republic of Trinidad and Tobago'),
('TV','TUV',798,'图瓦卢 Tuvalu','图瓦卢 Tuvalu'),
('TZ','TZA',834,'坦桑尼亚 Tanzania','坦桑尼亚联合共和国 United Republic of Tanzania'),
('UA','UKR',804,'乌克兰 Ukraine','乌克兰 Ukraine'),
('UG','UGA',800,'乌干达 Uganda','乌干达共和国 Republic of Uganda'),
('UM','UMI',581,'美属太平洋各群岛(包括:中途岛、约翰斯顿岛、豪兰岛、贝克岛和威克岛等) United States miscella-neous',''),
('US','USA',840,'美国 United States','美利坚合众国 United States of America'),
('UY','URY',858,'乌拉圭 Uruguay','乌拉圭东岸共和国 Oriental Republic of Uruguay'),
('UZ','UZB',860,'乌兹别克斯坦 Uzbekistan','乌兹别克斯坦共和国 Republic of Uzbekistan'),
('VA','VAT',336,'梵蒂冈 Vatican','梵蒂冈城国 Vatican City State'),
('VC','VCT',670,'圣文森特和格林纳丁斯 Saint Vincent and the Grenadines','圣文森特和格林纳丁斯 Saint Vincent and the Grenadines'),
('VE','VEN',862,'委内瑞拉 Venezuela','委内瑞拉共和国 Republic of Venezuela'),
('VG','VGB',92,'英属维尔京群岛 British Virgin Islands','英属维尔京群岛 British Virgin Islands'),
('VI','VIR',850,'美属维尔京群岛 United States Virgin Is-lands','美属维尔京群岛 United States Virgin Islands'),
('VN','VNM',704,'越南 Viet Nam','越南社会主席共和国 Socialist Republic of Viet Nam'),
('VU','VUT',548,'瓦努阿图 Vanuatu','瓦努阿图共和国 Republic of Vanuatu'),
('WF','WLF',876,'瓦利斯和富图纳群岛 Wallis and Futuna Is-lands','瓦利斯和富图纳群岛 Wallis and Futuna Islands'),
('WS','WSM',882,'西萨摩亚 Western Samoa','西萨摩亚独立国 Independent State of Western Samoa'),
('YE','YEM',887,'也门 Yemen','也门共和国 Republic of Yemen'),
('YT','MYT',175,'马约特 Mayotte','马约特 Mayotte'),
('YU','YUG',891,'南斯拉夫 Yugoslavia','南斯拉夫联盟共和国 Federal Republic of Yugoslavia'),
('ZA','ZAF',710,'南非 South Africa','南非共和国 Republic of South Africa'),
('ZM','ZMB',894,'赞比亚 Zambia','赞比亚共和国 Republic of Zambia'),
('ZR','ZAR',180,'扎伊尔 Zaire','扎伊尔共和国 Republic of Zaire'),
('ZW','ZWE',716,'津巴布韦 Zimbabwe','津巴布韦共和国 Republic of Zimbabwe');
