DROP TABLE IF EXISTS `st`.`G_DETAIL_SUSPENSION`;
CREATE TABLE  `st`.`G_DETAIL_SUSPENSION` (
  `STOCK_CODE` varchar(10) NOT NULL,
  `DATE_ID` int(10) unsigned NOT NULL,
  `BALANCE` int(10) unsigned NOT NULL,
  PRIMARY KEY (`STOCK_CODE`,`DATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;