

DROP TABLE IF EXISTS `st`.`G_STOCK_DAY`;
CREATE TABLE  `st`.`G_STOCK_DAY` (
  `STOCK` int(10) unsigned NOT NULL,
  `DATE` date NOT NULL,
  `OPEN` double(5,2) NOT NULL COMMENT '开盘价',
  `HIGH` double(5,2) NOT NULL COMMENT '最高价',
  `LOW` double(5,2) NOT NULL COMMENT '最低价',
  `CLOSE` double(5,2) NOT NULL COMMENT '收盘价',
  `VOLUME` int(10) unsigned NOT NULL COMMENT '成交量',
  `ADJ_CLOSE` double(5,2) NOT NULL COMMENT '原义为修正后的收盘价',
  PRIMARY KEY (`STOCK`,`DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
PARTITION BY RANGE  (YEAR(DATE)) ( 
	PARTITION p2009 VALUES LESS THAN (2009) ENGINE = InnoDB,
	PARTITION p2010 VALUES LESS THAN (2010) ENGINE = InnoDB,
	PARTITION p2011 VALUES LESS THAN (2011) ENGINE = InnoDB,
	PARTITION p2012 VALUES LESS THAN (2012) ENGINE = InnoDB,
	PARTITION p2013 VALUES LESS THAN (2013) ENGINE = InnoDB,
	PARTITION p2014 VALUES LESS THAN (2014) ENGINE = InnoDB,
	PARTITION p2015 VALUES LESS THAN (2015) ENGINE = InnoDB
);